Repository cythral/lambdajection, pull requests merged in 2021-02, with the labels that each got.

#106 LAMBJ-108 Response Status Serialization
  src/CustomResource/CustomResourceResponseStatus.cs
  src/CustomResource/CustomResourceResponseStatusConverter.cs
  tests/Compilation/Tests/CustomResourcesTests.cs
  tests/Compilation/Tests/Setup.cs
  tests/Setup.cs
  tests/Unit/CustomResource/CustomResourceResponseStatusConverterTests.cs
Labels: enhancement

#107 LAMBJ-109 Custom Resource End to End Test
  examples/AwsClientFactories/AwsClientFactories.csproj
  examples/CustomConfiguration/CustomConfiguration.csproj
  examples/CustomResource/CustomResource.csproj
  examples/CustomResource/Options.cs
  examples/CustomResource/PasswordGenerator.cs
  examples/CustomResource/Request.cs
  examples/CustomResource/Response.cs
  examples/CustomResource/Startup.cs
  examples/CustomResource/cloudformation.config.json
  examples/CustomResource/cloudformation.template.yml
  examples/CustomRuntime/CustomRuntime.csproj
  examples/Directory.Build.props
  examples/Directory.Build.targets
  examples/EncryptedOptions/EncryptedOptions.csproj
  examples/examples.sln
  src/CustomResource/CustomResourceRequestType.cs
  tests/Unit/CustomResource/CustomResourceRequestTypeTests.cs
Labels: enhancement

#108 v0.7.0-beta2 Release Preparations
  .github/releases/v0.7.0-beta2.md
  version.json
Labels: enhancement

#109 Turn on all E2E Tests
  examples/AwsClientFactories/AwsClientFactories.csproj
  examples/CustomConfiguration/CustomConfiguration.csproj
  examples/CustomRuntime/CustomRuntime.csproj
  examples/CustomSerializer/CustomSerializer.csproj
  examples/EncryptedOptions/EncryptedOptions.csproj
Labels: enhancement

#112 Automatic update of Amazon.Lambda.ApplicationLoadBalancerEvents to 2.1.0
  examples/CustomSerializer/CustomSerializer.csproj
Labels: nukeeper

#111 Automatic update of coverlet.collector to 3.0.2
  tests/Tests.csproj
  tests/packages.lock.json
Labels: nukeeper

#110 Automatic update of Microsoft.Extensions.Configuration.Json to 5.0.0
  examples/CustomConfiguration/CustomConfiguration.csproj
  tests/Compilation/Projects/ConfigFactory/ConfigFactory.csproj
Labels: nukeeper

#114 Automatic update of NuGet.ProjectModel to 5.9.0-rc.7046
  tests/Tests.csproj
  tests/packages.lock.json
Labels: nukeeper

#113 Automatic update of Microsoft.Build.Locator to 1.4.1
  tests/Tests.csproj
  tests/packages.lock.json
Labels: nukeeper

#119 Automatic update of AWSSDK.SecurityToken to 3.5.1.45
  tests/Tests.csproj
  tests/packages.lock.json
Labels: nukeeper

#116 Automatic update of NUnit to 3.13.1
  tests/Tests.csproj
  tests/packages.lock.json
Labels: nukeeper

#118 Automatic update of AWSSDK.S3 to 3.5.7.12
  tests/Tests.csproj
  tests/packages.lock.json
Labels: nukeeper

#120 Automatic update of AWSSDK.Core to 3.5.2.5
  src/Core/Core.csproj
  src/Core/packages.lock.json
  src/Generator/Generator.csproj
  src/Generator/packages.lock.json
  src/Metapackage/packages.lock.json
  tests/packages.lock.json
Labels: nukeeper

#124 Automatic update of AWSSDK.S3 to 3.5.8
  tests/Tests.csproj
  tests/packages.lock.json
Labels: nukeeper

#125 Automatic update of NuGet.ProjectModel to 5.9.0-rc.7097
  tests/Tests.csproj
  tests/packages.lock.json
Labels: nukeeper

#123 Automatic update of AWSSDK.KeyManagementService to 3.5.2.6
  src/Encryption/Encryption.csproj
  src/Encryption/packages.lock.json
  src/Generator/packages.lock.json
  src/Layer/Manifest/Manifest.csproj
  src/Metapackage/packages.lock.json
  tests/packages.lock.json
Labels: nukeeper

#126 LAMBJ-115 Automatically Determine AWSSDK.Core Version for Layer
  src/Layer/Layer.csproj
  src/Layer/Manifest/Manifest.csproj
  src/Layer/packages.lock.json
Labels: enhancement

#127 Updates for Release Notes
  .github/releases/v0.7.0-beta2.md
Labels: enhancement

#128 Nukeeper Account Update
  .github/workflows/dependency-updates.yml
Labels: enhancement

#129 LAMBJ-100 Discord Notifications
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/dependency-updates.yml
Labels: enhancement

#139 Dependency Simplifications
  .github/releases/v0.7.0-beta2.md
  src/Generator/Generator.csproj
  src/Generator/packages.lock.json
  src/Layer/Layer.csproj
  src/Metapackage/packages.lock.json
  tests/packages.lock.json
Labels: enhancement, housekeeping

#144 LAMBJ-113 Remove Unused CodeQL Step
  .github/workflows/codeql-analysis.yml
Labels: housekeeping

#145 LAMBJ-118 Dont Write Null PhysicalResourceIds
  .github/releases/v0.7.0-beta2.md
  src/Core/DefaultHttpClient.cs
  tests/Compilation/Tests/CustomResourcesTests.cs
Labels: bug

#151 Auto Assign PRs
  .github/auto_assign.yml
  .github/workflows/assign-prs.yml
Labels: housekeeping

#157 LAMBJ-120 Automatic Data Annotation Property Validation
  .github/releases/v0.7.0-beta2.md
  CONTRIBUTING.md
  examples/AwsClientFactories/AwsClientFactories.csproj
  examples/AwsClientFactories/Request.cs
  examples/CustomResource/CustomResource.csproj
  examples/CustomResource/Request.cs
  src/Core/DefaultLambdaHost.cs
  src/Core/ILambda.cs
  src/Core/LambdaHostBase.cs
  src/CustomResource/CustomResourceLambdaHost.cs
  src/CustomResource/ICustomResourceProvider.cs
  src/Generator/Generator.csproj
  src/Generator/InterfaceImplementationAnalyzer.cs
  src/Generator/LambdaGenerator.cs
  src/Generator/UnitGenerator.cs
  src/Generator/Utils/TypeUtils.cs
  src/Generator/ValidationsGenerator.cs
  src/Generator/packages.lock.json
  src/Metapackage/packages.lock.json
  tests/Common/AutoAttribute.cs
  tests/Common/TestCustomResourceLambda.cs
  tests/Common/TestLambda.cs
  tests/Compilation/Projects/CustomResources/CustomResources.csproj
  tests/Compilation/Projects/CustomResources/ResourceProperties.cs
  tests/Compilation/Tests/CustomResourcesTests.cs
  tests/Compilation/Utils/GenerateAssemblyResult.cs
  tests/Compilation/Utils/MSBuildProjectExtensions.cs
  tests/Unit/Generator/TypeUtilsTests.cs
  tests/Utils/CompilationExtensions.cs
  tests/Utils/GenerateAssemblyResult.cs
  tests/packages.lock.json
Labels: enhancement

#167 Fix E2E Tests
  examples/Directory.Build.targets
Labels: bug

#168 v0.7.0-beta3 Release Preparations
  .github/releases/v0.7.0-beta3.md
  version.json
Labels: housekeeping

#169 v0.7.0-beta2 Hotfixes
  .github/releases/v0.7.0-beta3.md
  src/Generator/ValidationsGenerator.cs
  tests/Compilation/Projects/CustomResources/ResourceProperties.cs
Labels: bug

#170 v0.7.0-beta4 Prep
  .github/releases/v0.7.0-beta4.md
  version.json
Labels: housekeeping
